### ISSUE TITLE
Text search having trouble with some single words

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#464]
http://staging.vault.factcheckinsights.org/

Put trump in search box - button flickers but nothing happens on return or click (same for searching just biden)

**Comment by reefdog** [comment]
I accidentally think I figured out what's going on with each of these, from some other work I'm doing.

- `trump` is due to a bug in the template code for Facebook users. This is about to get fixed in a PR I'm doing for #477.
- `biden` is due to a bug in the `FacebookPost` model, where `reactions` is nil so the `number_of_likes` method errors out. This will probably get fixed when I redo search results in #473, although this certainly shouldn't have been causing an error. (We either need a fallback or something.)
