### ISSUE TITLE
Investigate hello@factcheckinsights.org

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#523]
Chris received the test email Erica sent to this address on 5/16. Not sure how/where the account is set up. Ideally, Joel and Erica would receive these emails as well.

**Comment by ericaryan** [comment]
Joel also received the test email sent 5/16. So it looks like it's just me who needs to be added.

**Comment by ericaryan** [comment]
Issue with receiving emails from users:

Users who are approved as Fact-Check Insights users are not automatically granted MediaVault access (as intended). But if they want to request access, they can use the "Request Access" button on vault.factcheckinsights.org. This generates a pre-filled email that can be sent to our team to request access.

In testing, the email that I sent from elryan+fci@gmail.com was received by Chris using the hello@factcheckinsights.org address, but the one that Asa sent using his Duke email address was not received. Perhaps there's a spam filter or setting we need to investigate as well?

**Comment by cguess** [comment]
I've looked into this. @ericaryan @joelwluther and I's emails addresses are all set up. Mailgun (which handles the forwarding of emails) doesn't have any configurable spam protection. We'd have to  test further with Asa, because there's not much else I can do at this point? Email is a finicky and terrible system unfortunately. We may want to have it notify a Slack channel as well?
