### ISSUE TITLE
Fix scraping of mediaLink vs. originalMediaLink

### ISSUE THREAD

**Issue by joelwluther** [TechAndCheck/zenodotus#559]
From #550 

–––

Okay, it also appears we're scraping the originalMediaLink as opposed to the mediaLink. (We should be scraping mediaLink.)

Here's an example:

https://vault.factcheckinsights.org/media/052e844e-54f5-44de-a45c-a47de743bcbd

The mediaLink in the schema is:

https://www.instagram.com/reel/CnQ5Zxuqrz-/?utm_source=ig_embed&ig_rid=876169f7-eeb5-4646-b127-5c15c4e30306

The originalMediaLink is:

https://www.youtube.com/watch?v=zIwLWfaAg-8

We're (incorrectly) scraping the YouTube link and showing that as "mediaLink" -- we should be scraping the Instagram link and showing that link as mediaLink.

**Comment by cguess** [comment]
OK, this is where this is happening https://github.com/TechAndCheck/zenodotus/blob/a07c1e5dc7a24fed3bc8631a593e2f40639957ba/app/models/archive_item.rb#L23

**Comment by cguess** [comment]
OK, a few notes for myself here. Note: this is for Google's format since it's the only one we're actively importing at the moment. FactStream's will be different and we'll cross that rubicon when it comes to it

- [ ] Create a new variable on the `MediaReview` class called `media_url` to hold the url we actually, want to scrape
- [ ] Given the following MedaiReview Structure: 
    ```
    {
          "@context" : "http://schema.org",
          "@type" : "MediaReview",
          "author" : 
          {
            "@type" : "Organization",
            "name" : "Factcheck Lab \u4e8b\u5be6\u67e5\u6838\u5be6\u9a57\u5ba4",
            "url" : "https://www.factchecklab.org/"
          },
          "datePublished" : "2023-05-25",
          "itemReviewed" : 
          {
            "@type" : "ImageObject",
            "contentUrl" : "https://scontent-hkg4-2.xx.fbcdn.net/v/t39.30808-6/347243637_1246822852640661_5850421334356597725_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=12KXf57RwfEAX9IOaoP&_nc_ht=scontent-hkg4-2.xx&oh=00_AfDGg2y4zuM8AycExsPPdsX-5xS5RwC1sdlJHLyC0M15tg&oe=648D1B56"
          },
          "mediaAuthenticityCategory" : 
          [
            "DecontextualizedContent"
          ],
          "originalMediaContextDescription" : "Screen capture from Amerika music video (song by Rammstein) ",
          "originalMediaLink" : "https://www.youtube.com/watch?v=Rr8ljRgcJNM",
          "sdPublisher" : 
          {
            "@type" : "Organization",
            "name" : "Google Fact Check Tools",
            "url" : "https://g.co/factchecktools"
          },
          "url" : "https://www.factchecklab.org/20230525/"
        }
    ```
    we extract the `itemReviewed` element:
    ```
    {
        "@type" : "ImageObject",
        "contentUrl" : "https://scontent-hkg4-2.xx.fbcdn.net/v/t39.30808-6/347243637_1246822852640661_5850421334356597725_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=12KXf57RwfEAX9IOaoP&_nc_ht=scontent-hkg4-2.xx&oh=00_AfDGg2y4zuM8AycExsPPdsX-5xS5RwC1sdlJHLyC0M15tg&oe=648D1B56"
    }
    ```
    and then pull `contentURL`
    ```
    "contentUrl" : "https://scontent-hkg4-2.xx.fbcdn.net/v/t39.30808-6/347243637_1246822852640661_5850421334356597725_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=12KXf57RwfEAX9IOaoP&_nc_ht=scontent-hkg4-2.xx&oh=00_AfDGg2y4zuM8AycExsPPdsX-5xS5RwC1sdlJHLyC0M15tg&oe=648D1B56"
```
- [ ] From there we set `MediaReview.media_url` to this url
- [ ] Adjust the `scrape` function in `MediaReview` so that `media_url` is what's sent off to the scrape queue
- [ ] Insure that `original_media_link` is properly set from the `originalMediaLink` element in the previous MediaReview JSON structure
- [ ] Adjust the JSON output blueprints so that `media_url` is added properly
- [ ] Update fixtures so that the correct links are in the right places for testing
- [ ] Update the `MediaReview` `Scrape` and `ArchiveItem` tests (at least
- [ ] Update integration controller tests to properly handle this new field and such
- [ ] Ensure tests run cleanly

**Comment by cguess** [comment]
After thinking about it for awhile I've decided instead of the back and forth and moving data around we're just going to wipe everything and rescrape from scratch. We're early enough.
